export interface Experience {
  id: string;
  slug: string;
  title: string;
  location: string;
  area: string;
  price: number;
  originalPrice?: number;
  rating: number;
  reviewCount: number;
  duration: string;
  category: string;
  image: string;
  images: string[];
  description: string;
  highlights: string[];
  freeCancellation: boolean;
  discount?: number;
}

export const categories = [
  { id: "theme-parks", label: "Theme Parks", icon: "🎢" },
  { id: "cruises", label: "Cruises", icon: "🚢" },
  { id: "cabarets", label: "Cabarets", icon: "🎭" },
  { id: "guided-tours", label: "Guided Tours", icon: "🗺️" },
  { id: "museums", label: "Museums", icon: "🏛️" },
  { id: "landmarks", label: "Landmarks", icon: "🗼" },
  { id: "dinner-cruises", label: "Dinner Cruises", icon: "🍽️" },
  { id: "day-trips", label: "Day Trips", icon: "🚌" },
  { id: "food-tours", label: "Food Tours", icon: "🥐" },
  { id: "walking-tours", label: "Walking Tours", icon: "👟" },
];

export const experiences: Experience[] = [
  {
    id: "1",
    slug: "disneyland-paris-1-day-ticket",
    title: "1-Day Ticket to Disneyland® Paris",
    location: "Paris",
    area: "Marne-la-Vallée",
    price: 7130,
    rating: 4.5,
    reviewCount: 25889,
    duration: "1 day",
    category: "theme-parks",
    image: "/images/disneyland-paris.png",
    images: [
      "/images/disneyland-paris.png",
      "/images/eiffel-tower.png",
      "/images/versailles.png",
    ],
    description: "Step into a magical world of thrilling rides, fairy-tale adventures, and unforgettable Disney charm. Experience the magic of Disneyland® Paris with a 1-day ticket that grants you access to Disneyland Park or Walt Disney Studios Park.",
    highlights: [
      "Access to Disneyland Park or Walt Disney Studios Park",
      "Over 50 attractions, shows and experiences",
      "Meet your favorite Disney characters",
      "Spectacular parades and fireworks shows",
      "Iconic Sleeping Beauty Castle",
    ],
    freeCancellation: true,
    discount: undefined,
  },
  {
    id: "2",
    slug: "louvre-museum-reserved-access",
    title: "Louvre Museum Reserved Access Tickets",
    location: "Paris",
    area: "1st Arrondissement",
    price: 3639,
    originalPrice: 4851,
    rating: 4.2,
    reviewCount: 26777,
    duration: "2-3 hours",
    category: "museums",
    image: "/images/louvre.png",
    images: [
      "/images/louvre.png",
      "/images/orsay-museum.png",
    ],
    description: "Skip the queues and explore the world's largest art museum with reserved access tickets. Home to the Mona Lisa, Venus de Milo, and thousands of other masterpieces spanning thousands of years of human creativity.",
    highlights: [
      "Skip-the-line reserved entry",
      "Access to all permanent collections",
      "See the Mona Lisa and Venus de Milo",
      "Audio guide available",
      "Valid for entire day",
    ],
    freeCancellation: true,
    discount: 25,
  },
  {
    id: "3",
    slug: "eiffel-tower-madame-brasserie-lunch",
    title: "Lunch at Eiffel Tower's Madame Brasserie",
    location: "Paris",
    area: "7th Arrondissement",
    price: 7649,
    rating: 4.4,
    reviewCount: 912,
    duration: "2 hours",
    category: "dinner-cruises",
    image: "/images/eiffel-tower.png",
    images: [
      "/images/eiffel-tower.png",
      "/images/seine-river.png",
    ],
    description: "Reserve Madame Brasserie tickets for lunch or dinner inside the Eiffel Tower. Enjoy chef-curated French dining with iconic Paris views from the first floor of the world's most famous iron lattice structure.",
    highlights: [
      "Dining inside the Eiffel Tower",
      "Panoramic views of Paris",
      "Chef-curated French cuisine",
      "Sommelier-selected wine list",
      "Priority elevator access",
    ],
    freeCancellation: false,
  },
  {
    id: "4",
    slug: "disneyland-paris-seine-river-cruise-combo",
    title: "Combo: Disneyland® Paris Tickets + Seine River Cruise",
    location: "Paris",
    area: "Multiple",
    price: 9183,
    rating: 4.5,
    reviewCount: 25782,
    duration: "Full day",
    category: "theme-parks",
    image: "/images/seine-river.png",
    images: [
      "/images/seine-river.png",
      "/images/disneyland-paris.png",
    ],
    description: "Make the most of your Paris trip with this incredible combo that combines the magic of Disneyland® Paris with a scenic cruise along the Seine River.",
    highlights: [
      "1-day Disneyland® Paris ticket",
      "1-hour Seine River cruise",
      "Save vs. booking separately",
      "Flexible scheduling",
    ],
    freeCancellation: true,
  },
  {
    id: "5",
    slug: "bateaux-parisiens-seine-sightseeing",
    title: "Bateaux Mouches® Seine River 1-Hour Sightseeing Cruise with Live Commentary",
    location: "Paris",
    area: "8th Arrondissement",
    price: 1740,
    originalPrice: 1842,
    rating: 4.4,
    reviewCount: 4421,
    duration: "1 hour",
    category: "cruises",
    image: "/images/seine-river.png",
    images: [
      "/images/seine-river.png",
    ],
    description: "See Paris from a different perspective aboard the legendary Bateaux Mouches. Cruise past iconic landmarks including Notre-Dame, the Eiffel Tower, and the Louvre with live multilingual commentary.",
    highlights: [
      "Panoramic glass-covered boat",
      "Live commentary in 13 languages",
      "Pass 20+ Paris landmarks",
      "Evening illumination cruise available",
    ],
    freeCancellation: false,
    discount: 6,
  },
  {
    id: "6",
    slug: "eiffel-tower-guided-tour-seine-cruise-combo",
    title: "Combo: Eiffel Tower Guided Tour by Elevator with Seine River Cruise",
    location: "Paris",
    area: "7th Arrondissement",
    price: 4768,
    originalPrice: 6812,
    rating: 3.9,
    reviewCount: 2672,
    duration: "3 hours",
    category: "landmarks",
    image: "/images/eiffel-tower.png",
    images: [
      "/images/eiffel-tower.png",
    ],
    description: "Combine two iconic Paris experiences: a guided elevator tour of the Eiffel Tower and a relaxing Seine River cruise. Get the best views of the City of Light from above and below.",
    highlights: [
      "Skip-the-line Eiffel Tower access",
      "Expert English-speaking guide",
      "2nd floor observatory visit",
      "1-hour Seine River cruise",
    ],
    freeCancellation: false,
    discount: 30,
  },
  {
    id: "7",
    slug: "big-bus-paris-hop-on-hop-off",
    title: "Big Bus: Paris Hop-on Hop-off Bus Tour with Optional Seine River Cruise",
    location: "Paris",
    area: "Citywide",
    price: 4142,
    originalPrice: 5310,
    rating: 4.5,
    reviewCount: 4296,
    duration: "1 day",
    category: "guided-tours",
    image: "/images/seine-river.png",
    images: [
      "/images/seine-river.png",
    ],
    description: "Discover Paris at your own pace on the Big Bus hop-on hop-off tour. With stops at all major landmarks, recorded commentary in 14 languages, and an optional Seine cruise, this is the ultimate Paris overview.",
    highlights: [
      "24 or 48-hour pass",
      "2 bus routes covering 50+ stops",
      "Recorded commentary in 14 languages",
      "Optional Seine River cruise add-on",
    ],
    freeCancellation: false,
    discount: 22,
  },
  {
    id: "8",
    slug: "aquarium-de-paris-priority-access",
    title: "Aquarium de Paris Priority Access Tickets",
    location: "Paris",
    area: "16th Arrondissement",
    price: 2265,
    originalPrice: 2384,
    rating: 4.5,
    reviewCount: 1000,
    duration: "2 hours",
    category: "museums",
    image: "/images/aquarium.png",
    images: [
      "/images/aquarium.png",
    ],
    description: "Dive into the underwater world at Aquarium de Paris, one of Europe's largest aquariums. See over 10,000 sea creatures across 43 tanks including sharks, rays, jellyfish, and tropical fish.",
    highlights: [
      "Priority access tickets",
      "43 tanks with 10,000+ sea creatures",
      "Shark and ray tunnel",
      "Jellyfish gallery",
      "Interactive children's area",
    ],
    freeCancellation: false,
    discount: 5,
  },
  {
    id: "9",
    slug: "arc-de-triomphe-rooftop-eiffel-guided-combo",
    title: "Combo (Save 5%): Arc De Triomphe with Rooftop Access & Eiffel Tower Guided Tour by Elevator",
    location: "Paris",
    area: "8th Arrondissement",
    price: 5500,
    rating: 4.2,
    reviewCount: 26369,
    duration: "4 hours",
    category: "landmarks",
    image: "/images/arc-de-triomphe.png",
    images: [
      "/images/arc-de-triomphe.png",
    ],
    description: "Experience two of Paris' most iconic monuments in one unforgettable combo. Ascend the Arc de Triomphe for rooftop views down the Champs-Élysées, then explore the Eiffel Tower with an expert guide.",
    highlights: [
      "Arc de Triomphe rooftop access",
      "Eiffel Tower elevator guided tour",
      "Expert English guide",
      "5% savings vs booking separately",
    ],
    freeCancellation: false,
    discount: 5,
  },
  {
    id: "10",
    slug: "louvre-versailles-combo",
    title: "Combo (Save 9%): Louvre Museum Reserved Access + Versailles Palace Tickets",
    location: "Paris",
    area: "Multiple",
    price: 6200,
    rating: 4.2,
    reviewCount: 22075,
    duration: "Full day",
    category: "museums",
    image: "/images/versailles.png",
    images: [
      "/images/versailles.png",
    ],
    description: "Explore two of France's most spectacular royal palaces and art collections. Start with reserved access to the Louvre, then journey to the gilded splendour of the Palace of Versailles.",
    highlights: [
      "Louvre Museum reserved entry",
      "Palace of Versailles access",
      "Hall of Mirrors",
      "Royal Gardens access",
      "9% savings combo deal",
    ],
    freeCancellation: false,
    discount: 9,
  },
  {
    id: "11",
    slug: "crazy-horse-paris-tickets",
    title: "Crazy Horse Paris Tickets",
    location: "Paris",
    area: "8th Arrondissement",
    price: 12856,
    rating: 4.5,
    reviewCount: 1200,
    duration: "1.5 hours",
    category: "cabarets",
    image: "/images/cabaret.png",
    images: [
      "/images/cabaret.png",
    ],
    description: "Experience a daring cabaret with avant-garde performances and stunning artistic lighting at the legendary Crazy Horse Paris. A world-renowned show that has been dazzling audiences since 1951.",
    highlights: [
      "World-famous cabaret show",
      "Avant-garde artistic performances",
      "Stunning light and shadow effects",
      "Champagne packages available",
      "Iconic Paris nightlife experience",
    ],
    freeCancellation: false,
  },
  {
    id: "12",
    slug: "paradis-latin-tickets",
    title: "Paradis Latin Tickets",
    location: "Paris",
    area: "5th Arrondissement",
    price: 9723,
    rating: 4.3,
    reviewCount: 2100,
    duration: "2 hours",
    category: "cabarets",
    image: "/images/cabaret.png",
    images: [
      "/images/cabaret.png",
    ],
    description: "Immerse yourself in the most Parisian of all cabarets at the Paradis Latin, the oldest cabaret theater in Paris built by Gustave Eiffel himself. Spectacular costumes, stunning choreography, and French charm.",
    highlights: [
      "Historic cabaret venue by Gustave Eiffel",
      "Spectacular costume show",
      "French champagne included",
      "VIP table options",
    ],
    freeCancellation: false,
  },
  {
    id: "13",
    slug: "disneyland-paris-multi-day",
    title: "Multi-Day Ticket to Disneyland® Paris",
    location: "Paris",
    area: "Marne-la-Vallée",
    price: 18731,
    rating: 4.4,
    reviewCount: 4557,
    duration: "2-3 days",
    category: "theme-parks",
    image: "/images/disneyland-paris.png",
    images: [
      "/images/disneyland-paris.png",
    ],
    description: "Make the most of Disneyland® Paris with a multi-day ticket. Explore both Disneyland Park and Walt Disney Studios Park with access to over 100 attractions, shows, and entertainment.",
    highlights: [
      "Access to both Disney parks",
      "100+ attractions and shows",
      "Character meet and greets",
      "Disney parades and fireworks",
      "Best value for multiple days",
    ],
    freeCancellation: true,
  },
  {
    id: "14",
    slug: "parc-asterix-entry-tickets",
    title: "Parc Astérix Full-Day Entry Tickets",
    location: "Paris",
    area: "Plailly",
    price: 7363,
    rating: 4.5,
    reviewCount: 3981,
    duration: "1 day",
    category: "theme-parks",
    image: "/images/versailles.png",
    images: [
      "/images/versailles.png",
    ],
    description: "Experience the thrills of Parc Astérix, France's beloved theme park inspired by the famous Gauls. Enjoy over 40 attractions including rollercoasters, water rides, and live shows.",
    highlights: [
      "40+ attractions and rollercoasters",
      "Live shows and entertainment",
      "Meet Asterix and Obelix",
      "Suitable for all ages",
      "French food and dining",
    ],
    freeCancellation: false,
  },
  {
    id: "15",
    slug: "disneyland-flexible-date-ticket",
    title: "1-Day Flexible Date Ticket to Disneyland® Paris",
    location: "Paris",
    area: "Marne-la-Vallée",
    price: 14617,
    rating: 4.5,
    reviewCount: 2529,
    duration: "1 day",
    category: "theme-parks",
    image: "/images/disneyland-paris.png",
    images: [
      "/images/disneyland-paris.png",
    ],
    description: "Maximum flexibility for your Disneyland® Paris visit. Choose your date at the park gates, with access to both Disneyland Park and Walt Disney Studios. Perfect for unpredictable travel schedules.",
    highlights: [
      "Open-dated flexible ticket",
      "Access to both Disney parks",
      "No advance date commitment",
      "Valid for 1 year from purchase",
    ],
    freeCancellation: false,
  },
  {
    id: "16",
    slug: "paris-hop-on-hop-off-eiffel-combo",
    title: "Combo (Save 34%): Paris Hop-on Hop-off Bus Tour + Eiffel Tower Guided Tour with Summit Floor",
    location: "Paris",
    area: "Citywide",
    price: 7800,
    rating: 4.2,
    reviewCount: 7679,
    duration: "Full day",
    category: "guided-tours",
    image: "/images/eiffel-tower.png",
    images: [
      "/images/eiffel-tower.png",
    ],
    description: "Save big with this incredible combo that pairs a flexible hop-on hop-off bus tour with a guided Eiffel Tower experience including access to the summit floor for the best views in Paris.",
    highlights: [
      "Hop-on hop-off bus 24-hour pass",
      "Eiffel Tower summit floor access",
      "Expert licensed guide",
      "34% savings combo deal",
    ],
    freeCancellation: false,
    discount: 34,
  },
  {
    id: "17",
    slug: "orsay-museum-orangerie-combo",
    title: "Combo (Save 11%): Orsay Museum with Audio Guide + Orangerie Museum Tickets",
    location: "Paris",
    area: "7th Arrondissement",
    price: 3900,
    rating: 4.3,
    reviewCount: 4724,
    duration: "4 hours",
    category: "museums",
    image: "/images/orsay-museum.png",
    images: [
      "/images/orsay-museum.png",
    ],
    description: "Explore two of Paris' finest art museums in one day. The Musée d'Orsay houses the world's finest Impressionist collection, while the Orangerie is home to Monet's monumental Water Lilies paintings.",
    highlights: [
      "Orsay Museum with audio guide",
      "Orangerie Museum included",
      "Monet's Water Lilies",
      "World's best Impressionist collection",
      "11% combo savings",
    ],
    freeCancellation: false,
    discount: 11,
  },
  {
    id: "18",
    slug: "versailles-palace-guided-tour",
    title: "Palace of Versailles: Skip-the-Line Guided Tour",
    location: "Paris",
    area: "Versailles",
    price: 4200,
    rating: 4.6,
    reviewCount: 8932,
    duration: "3 hours",
    category: "guided-tours",
    image: "/images/versailles.png",
    images: [
      "/images/versailles.png",
    ],
    description: "Discover the opulent Palace of Versailles with a skip-the-line guided tour. Explore the glittering Hall of Mirrors, royal apartments, and stunning gardens of this UNESCO World Heritage Site.",
    highlights: [
      "Skip-the-line entry",
      "Expert guide included",
      "Hall of Mirrors",
      "Royal Apartments",
      "Gardens of Versailles",
    ],
    freeCancellation: true,
  },
  {
    id: "19",
    slug: "paris-food-tour-montmartre",
    title: "Montmartre Food & Wine Tour",
    location: "Paris",
    area: "18th Arrondissement",
    price: 3500,
    rating: 4.7,
    reviewCount: 1456,
    duration: "3 hours",
    category: "food-tours",
    image: "/images/food-tour.png",
    images: [
      "/images/food-tour.png",
    ],
    description: "Taste your way through the charming streets of Montmartre with a local food expert. Sample artisan cheeses, fresh baguettes, charcuterie, macarons, and wine at the best hidden spots.",
    highlights: [
      "8+ food and wine tastings",
      "Local expert guide",
      "Visit hidden food gems",
      "Learn about French culinary culture",
      "Small group (max 12 people)",
    ],
    freeCancellation: true,
  },
  {
    id: "20",
    slug: "sacre-coeur-walking-tour",
    title: "Sacré-Cœur & Montmartre Walking Tour",
    location: "Paris",
    area: "18th Arrondissement",
    price: 1800,
    rating: 4.5,
    reviewCount: 3201,
    duration: "2 hours",
    category: "walking-tours",
    image: "/images/eiffel-tower.png",
    images: [
      "/images/eiffel-tower.png",
    ],
    description: "Explore the artistic hilltop neighbourhood of Montmartre and iconic Sacré-Cœur Basilica with a knowledgeable local guide. Discover hidden streets, artists' studios, and the best panoramic views of Paris.",
    highlights: [
      "Sacré-Cœur Basilica visit",
      "Artists' quarter exploration",
      "Panoramic Paris views",
      "Small group walking tour",
      "Local insider stories",
    ],
    freeCancellation: true,
  },
  {
    id: "21",
    slug: "notre-dame-virtual-tour",
    title: "Notre-Dame Cathedral Area Walking Tour",
    location: "Paris",
    area: "4th Arrondissement",
    price: 1500,
    rating: 4.4,
    reviewCount: 2890,
    duration: "1.5 hours",
    category: "walking-tours",
    image: "/images/seine-river.png",
    images: [
      "/images/seine-river.png",
    ],
    description: "Explore the historic Île de la Cité and the area around the iconic Notre-Dame Cathedral. Learn about its history, architecture, and the dramatic 2019 fire and restoration with an expert guide.",
    highlights: [
      "Notre-Dame exterior tour",
      "Île de la Cité exploration",
      "Sainte-Chapelle exterior",
      "Expert architectural history",
    ],
    freeCancellation: true,
  },
  {
    id: "22",
    slug: "paris-night-tour-illuminations",
    title: "Paris by Night: City Illuminations Bus Tour",
    location: "Paris",
    area: "Citywide",
    price: 2200,
    rating: 4.6,
    reviewCount: 5432,
    duration: "2 hours",
    category: "guided-tours",
    image: "/images/seine-river.png",
    images: [
      "/images/seine-river.png",
    ],
    description: "See Paris sparkle after dark on this magical evening bus tour. Watch the Eiffel Tower's iconic light show, cruise past illuminated monuments, and experience the City of Light at its most romantic.",
    highlights: [
      "Eiffel Tower light show",
      "Champs-Élysées illuminations",
      "Louvre and Notre-Dame by night",
      "Multilingual audio commentary",
      "Comfortable double-decker bus",
    ],
    freeCancellation: true,
  },
  {
    id: "23",
    slug: "moulin-rouge-show-tickets",
    title: "Moulin Rouge® Paris Show Tickets",
    location: "Paris",
    area: "9th Arrondissement",
    price: 11500,
    rating: 4.6,
    reviewCount: 3847,
    duration: "1.5 hours",
    category: "cabarets",
    image: "/images/cabaret.png",
    images: [
      "/images/cabaret.png",
    ],
    description: "Experience the world-famous Moulin Rouge show in Paris, the birthplace of the Can-Can dance. An extravaganza of feathers, sequins, and Champagne that has entertained audiences since 1889.",
    highlights: [
      "World-famous Féerie show",
      "Champagne included",
      "Original Can-Can performances",
      "Legendary windmill venue",
      "60 Doris Girls performers",
    ],
    freeCancellation: false,
  },
  {
    id: "24",
    slug: "catacombs-paris-tickets",
    title: "Paris Catacombs: Skip-the-Line Entry Ticket",
    location: "Paris",
    area: "14th Arrondissement",
    price: 1950,
    rating: 4.3,
    reviewCount: 12500,
    duration: "1 hour",
    category: "landmarks",
    image: "/images/arc-de-triomphe.png",
    images: [
      "/images/arc-de-triomphe.png",
    ],
    description: "Descend into the world's most famous ossuary beneath the streets of Paris. Skip the long queues and explore the haunting underground tunnels housing the remains of over 6 million Parisians.",
    highlights: [
      "Skip-the-line entry",
      "6 million remains on display",
      "20m underground tunnel network",
      "Audio guide available",
      "Eerie and unforgettable experience",
    ],
    freeCancellation: true,
  },
  {
    id: "25",
    slug: "eiffel-tower-summit-tickets",
    title: "Eiffel Tower: Direct Access to the Summit",
    location: "Paris",
    area: "7th Arrondissement",
    price: 3781,
    rating: 4.5,
    reviewCount: 18943,
    duration: "2-3 hours",
    category: "landmarks",
    image: "/images/eiffel-tower.png",
    images: [
      "/images/eiffel-tower.png",
    ],
    description: "Soar to the very top of the Eiffel Tower with direct access to the summit at 300m above Paris. Enjoy unrivalled 360° panoramic views from the most iconic landmark in the world.",
    highlights: [
      "Direct summit (3rd floor) access",
      "300m above Paris",
      "360° panoramic views",
      "Gustave Eiffel's private apartment",
      "Champagne bar at the top",
    ],
    freeCancellation: true,
  },
  {
    id: "26",
    slug: "seine-dinner-cruise-bateaux",
    title: "Bateaux Parisiens: Seine Dinner Cruise",
    location: "Paris",
    area: "7th Arrondissement",
    price: 8900,
    rating: 4.3,
    reviewCount: 6234,
    duration: "2.5 hours",
    category: "dinner-cruises",
    image: "/images/seine-river.png",
    images: [
      "/images/seine-river.png",
    ],
    description: "Drift along the Seine while dining on exquisite French cuisine with panoramic views of Paris's illuminated monuments. A truly romantic evening experience on the world's most beautiful river.",
    highlights: [
      "Gourmet French dinner",
      "Live music and entertainment",
      "Panoramic glass boat",
      "Eiffel Tower light show views",
      "Champagne toast",
    ],
    freeCancellation: true,
  },
  {
    id: "27",
    slug: "musee-dorsay-skip-the-line",
    title: "Musée d'Orsay: Skip-the-Line Tickets",
    location: "Paris",
    area: "7th Arrondissement",
    price: 2100,
    rating: 4.5,
    reviewCount: 9876,
    duration: "2 hours",
    category: "museums",
    image: "/images/orsay-museum.png",
    images: [
      "/images/orsay-museum.png",
    ],
    description: "Explore the world's greatest collection of Impressionist and Post-Impressionist art at the Musée d'Orsay. See masterpieces by Monet, Renoir, Van Gogh, Degas, and Cézanne.",
    highlights: [
      "World's finest Impressionist collection",
      "Skip-the-line entry",
      "Monet, Van Gogh, Renoir originals",
      "Stunning Beaux-Arts station building",
    ],
    freeCancellation: true,
  },
  {
    id: "28",
    slug: "paris-day-trip-mont-saint-michel",
    title: "Day Trip from Paris to Mont Saint-Michel",
    location: "Paris",
    area: "Normandy",
    price: 6800,
    rating: 4.4,
    reviewCount: 4312,
    duration: "Full day",
    category: "day-trips",
    image: "/images/versailles.png",
    images: [
      "/images/versailles.png",
    ],
    description: "Journey to the magical island abbey of Mont Saint-Michel, one of France's most spectacular sights. Rising from the sea on a rocky island, this medieval masterpiece is a UNESCO World Heritage Site.",
    highlights: [
      "Round-trip transport from Paris",
      "UNESCO World Heritage Site",
      "Medieval abbey exploration",
      "Expert guide included",
      "Scenic Normandy countryside",
    ],
    freeCancellation: true,
  },
  {
    id: "29",
    slug: "paris-day-trip-loire-valley",
    title: "Day Trip from Paris: Loire Valley Châteaux Tour",
    location: "Paris",
    area: "Loire Valley",
    price: 5500,
    rating: 4.5,
    reviewCount: 3124,
    duration: "Full day",
    category: "day-trips",
    image: "/images/versailles.png",
    images: [
      "/images/versailles.png",
    ],
    description: "Discover the fairytale châteaux of the Loire Valley, France's royal heartland. Visit the stunning Chambord and Chenonceau, surrounded by the region's famous vineyards and gardens.",
    highlights: [
      "Visit 2-3 Loire châteaux",
      "Château de Chambord",
      "Château de Chenonceau",
      "Wine tasting included",
      "Expert guide",
    ],
    freeCancellation: true,
  },
  {
    id: "30",
    slug: "paris-cooking-class",
    title: "Parisian Cooking Class: Croissants & French Pastries",
    location: "Paris",
    area: "Le Marais",
    price: 4500,
    rating: 4.8,
    reviewCount: 892,
    duration: "3 hours",
    category: "food-tours",
    image: "/images/food-tour.png",
    images: [
      "/images/food-tour.png",
    ],
    description: "Learn the art of French pastry-making in a hands-on cooking class in the heart of Paris. A professional pastry chef will teach you to craft perfect croissants, macarons, and classic French tarts.",
    highlights: [
      "Hands-on pastry class",
      "Professional pastry chef instructor",
      "Make croissants and macarons",
      "Eat everything you make",
      "Recipe cards to take home",
    ],
    freeCancellation: true,
  },
];
